// Refactored formal register phrases with suggestions
// Only root forms included - grammatical variants handled by Smart Regex
export const FORMAL_REGISTER_PHRASES = [
  // High Severity - AI-Generated Clichés
  { phrase: "delve", category: "cliché", weight: 3, suggestion: "investigate" },
  { phrase: "tapestry", category: "cliché", weight: 3, suggestion: "variety" },
  { phrase: "testament", category: "cliché", weight: 3, suggestion: "evidence" },
  { phrase: "beacon", category: "cliché", weight: 3, suggestion: "example" },
  { phrase: "multifaceted", category: "cliché", weight: 3, suggestion: "complex" },
  { phrase: "ever-evolving", category: "cliché", weight: 3, suggestion: "changing" },
  { phrase: "myriad", category: "cliché", weight: 3, suggestion: "many" },
  { phrase: "plethora", category: "cliché", weight: 3, suggestion: "abundance" },
  { phrase: "paradigm shift", category: "cliché", weight: 3, suggestion: "major change" },
  { phrase: "symbiotic", category: "cliché", weight: 3, suggestion: "mutually beneficial" },
  { phrase: "embark", category: "cliché", weight: 3, suggestion: "begin" },

  // Medium Severity - Formulaic Business Language
  { phrase: "dive deep", category: "cliché", weight: 2, suggestion: "examine closely" },
  { phrase: "landscape", category: "cliché", weight: 2, suggestion: "field" },
  { phrase: "rapidly evolving", category: "cliché", weight: 2, suggestion: "changing quickly" },
  { phrase: "dynamic", category: "cliché", weight: 2, suggestion: "active" },
  { phrase: "realm", category: "cliché", weight: 2, suggestion: "area" },
  { phrase: "cornerstone", category: "cliché", weight: 2, suggestion: "foundation" },
  { phrase: "pinnacle", category: "cliché", weight: 2, suggestion: "peak" },
  { phrase: "game-changer", category: "cliché", weight: 2, suggestion: "significant innovation" },
  { phrase: "leverage", category: "cliché", weight: 2, suggestion: "use" },
  { phrase: "harness", category: "cliché", weight: 2, suggestion: "use" },
  { phrase: "unleash", category: "cliché", weight: 2, suggestion: "release" },
  { phrase: "unlock", category: "cliché", weight: 2, suggestion: "reveal" },
  { phrase: "elevate", category: "cliché", weight: 2, suggestion: "improve" },
  { phrase: "revolutionize", category: "cliché", weight: 2, suggestion: "transform" },
  { phrase: "transformative", category: "cliché", weight: 2, suggestion: "changing" },
  { phrase: "foster", category: "cliché", weight: 2, suggestion: "encourage" },
  { phrase: "cultivate", category: "cliché", weight: 2, suggestion: "develop" },
  { phrase: "spearhead", category: "cliché", weight: 2, suggestion: "lead" },
  { phrase: "orchestrate", category: "cliché", weight: 2, suggestion: "organize" },
  { phrase: "navigate", category: "cliché", weight: 2, suggestion: "move through" },
  { phrase: "journey", category: "cliché", weight: 2, suggestion: "process" },
  { phrase: "shed light on", category: "cliché", weight: 2, suggestion: "clarify" },
  { phrase: "underscore", category: "cliché", weight: 2, suggestion: "emphasize" },
  { phrase: "intersection", category: "cliché", weight: 2, suggestion: "overlap" },
  { phrase: "interplay", category: "cliché", weight: 2, suggestion: "interaction" },
  { phrase: "synergy", category: "cliché", weight: 2, suggestion: "cooperation" },
  { phrase: "nuance", category: "cliché", weight: 2, suggestion: "subtlety" },
  { phrase: "holistic", category: "cliché", weight: 2, suggestion: "comprehensive" },
  { phrase: "paradigm", category: "cliché", weight: 2, suggestion: "model" },

  // Low Severity - Academic Transitions & Hedging
  { phrase: "comprehensive", category: "academic", weight: 1, suggestion: "complete" },
  { phrase: "crucial", category: "academic", weight: 1, suggestion: "important" },
  { phrase: "pivotal", category: "academic", weight: 1, suggestion: "key" },
  { phrase: "vital", category: "academic", weight: 1, suggestion: "essential" },
  { phrase: "it is important to note", category: "hedging", weight: 1, suggestion: "note that" },
  { phrase: "it is worth noting", category: "hedging", weight: 1, suggestion: "notably" },
  { phrase: "in terms of", category: "hedging", weight: 1, suggestion: "regarding" },
  { phrase: "with regard to", category: "transition", weight: 1, suggestion: "about" },
  { phrase: "with respect to", category: "transition", weight: 1, suggestion: "concerning" },
  { phrase: "in light of", category: "transition", weight: 1, suggestion: "considering" },
  { phrase: "plays a crucial role", category: "emphasis", weight: 2, suggestion: "is important for" },
  { phrase: "plays a vital role", category: "emphasis", weight: 2, suggestion: "is essential for" },
  { phrase: "plays a pivotal role", category: "emphasis", weight: 2, suggestion: "is key for" },
  { phrase: "it is essential to", category: "hedging", weight: 1, suggestion: "must" },
  { phrase: "it is crucial to", category: "hedging", weight: 1, suggestion: "should" },
  { phrase: "in conclusion", category: "transition", weight: 1, suggestion: "finally" },
  { phrase: "to summarize", category: "transition", weight: 1, suggestion: "in summary" },
  { phrase: "first and foremost", category: "emphasis", weight: 2, suggestion: "first" },
  { phrase: "comprehensive understanding", category: "academic", weight: 2, suggestion: "full understanding" },
  { phrase: "holistic approach", category: "academic", weight: 2, suggestion: "complete approach" },
  { phrase: "facilitate", category: "academic", weight: 1, suggestion: "help" },
  { phrase: "utilize", category: "academic", weight: 1, suggestion: "use" },
  { phrase: "implement", category: "academic", weight: 1, suggestion: "apply" },
];

export const CONNECTIVES = {
  additive: ["and", "also", "moreover", "furthermore", "additionally", "besides", "likewise", "similarly"],
  adversative: ["but", "however", "yet", "nevertheless", "nonetheless", "although", "though", "whereas", "while", "conversely"],
  causal: ["because", "therefore", "thus", "hence", "consequently", "accordingly", "so", "since"],
  temporal: ["then", "next", "finally", "subsequently", "meanwhile", "afterward", "previously", "first", "second", "third"],
};

export const HIGH_FREQUENCY_WORDS = new Set([
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "i", "it", "for",
  "not", "on", "with", "he", "as", "you", "do", "at", "this", "but", "his", "by",
  "from", "they", "we", "say", "her", "she", "or", "an", "will", "my", "one",
  "all", "would", "there", "their", "what", "so", "up", "out", "if", "about",
  "who", "get", "which", "go", "me", "when", "make", "can", "like", "time", "no",
  "just", "him", "know", "take", "people", "into", "year", "your", "good", "some",
  "could", "them", "see", "other", "than", "then", "now", "look", "only", "come",
  "its", "over", "think", "also", "back", "after", "use", "two", "how", "our",
  "work", "first", "well", "way", "even", "new", "want", "because", "any", "these",
  "give", "day", "most", "us", "is", "are", "was", "were", "been", "being", "has",
  "had", "does", "did", "am", "very", "more", "much", "such", "own", "same",
  "should", "must", "may", "might", "still", "here", "where", "why", "each",
  "every", "both", "few", "many",
]);

export const FORMULAIC_NGRAMS = {
  bigrams: [
    "it is", "this is", "there are", "there is", "we can", "you can",
    "in order", "as well", "such as", "due to", "based on", "in the",
    "of the", "to the", "for the", "on the", "by the", "with the",
    "is a", "are a", "was a", "be a", "as a", "have a",
    "important to", "necessary to", "essential to", "crucial to",
    "ability to", "order to", "need to", "want to", "have to",
    "can be", "will be", "would be", "could be", "should be", "must be",
  ],
  trigrams: [
    "it is important", "it is essential", "it is crucial", "it is necessary",
    "in order to", "as well as", "due to the", "based on the",
    "one of the", "some of the", "many of the", "most of the",
    "the fact that", "in the context", "on the other", "at the same",
    "is one of", "are some of", "is a key", "plays a crucial",
    "plays a vital", "plays an important", "in this article",
    "in this essay", "we will explore", "let us delve", "let's explore",
    "when it comes", "it comes to", "comes to the",
  ],
};
