// Refactored formal register phrases with suggestions
// Only root forms included - grammatical variants handled by Smart Regex
export const FORMAL_REGISTER_PHRASES = [
  { phrase: "delve", category: "cliché", weight: 3 },
  { phrase: "tapestry", category: "cliché", weight: 3 },
  { phrase: "testament", category: "cliché", weight: 3 },
  { phrase: "beacon", category: "cliché", weight: 3 },
  { phrase: "multifaceted", category: "cliché", weight: 3 },
  { phrase: "ever-evolving", category: "cliché", weight: 3 },
  { phrase: "myriad", category: "cliché", weight: 3 },
  { phrase: "plethora", category: "cliché", weight: 3 },
  { phrase: "paradigm shift", category: "cliché", weight: 3 },
  { phrase: "symbiotic", category: "cliché", weight: 3 },
  { phrase: "embark", category: "cliché", weight: 3 },

  // Medium Severity - Formulaic Business Language
  { phrase: "dive deep", category: "cliché", weight: 2 },
  { phrase: "landscape", category: "cliché", weight: 2 },
  { phrase: "rapidly evolving", category: "cliché", weight: 2 },
  { phrase: "dynamic", category: "cliché", weight: 2 },
  { phrase: "realm", category: "cliché", weight: 2 },
  { phrase: "cornerstone", category: "cliché", weight: 2 },
  { phrase: "pinnacle", category: "cliché", weight: 2 },
  { phrase: "game-changer", category: "cliché", weight: 2 },
  { phrase: "leverage", category: "cliché", weight: 2 },
  { phrase: "harness", category: "cliché", weight: 2 },
  { phrase: "unleash", category: "cliché", weight: 2 },
  { phrase: "unlock", category: "cliché", weight: 2 },
  { phrase: "elevate", category: "cliché", weight: 2 },
  { phrase: "revolutionize", category: "cliché", weight: 2 },
  { phrase: "transformative", category: "cliché", weight: 2 },
  { phrase: "foster", category: "cliché", weight: 2 },
  { phrase: "cultivate", category: "cliché", weight: 2 },
  { phrase: "spearhead", category: "cliché", weight: 2 },
  { phrase: "orchestrate", category: "cliché", weight: 2 },
  { phrase: "navigate", category: "cliché", weight: 2 },
  { phrase: "journey", category: "cliché", weight: 2 },
  { phrase: "shed light on", category: "cliché", weight: 2 },
  { phrase: "underscore", category: "cliché", weight: 2 },
  { phrase: "intersection", category: "cliché", weight: 2 },
  { phrase: "interplay", category: "cliché", weight: 2 },
  { phrase: "synergy", category: "cliché", weight: 2 },
  { phrase: "nuance", category: "cliché", weight: 2 },
  { phrase: "holistic", category: "cliché", weight: 2 },
  { phrase: "paradigm", category: "cliché", weight: 2 },

  // Low Severity - Academic Transitions & Hedging
  { phrase: "comprehensive", category: "academic", weight: 1 },
  { phrase: "crucial", category: "academic", weight: 1 },
  { phrase: "pivotal", category: "academic", weight: 1 },
  { phrase: "vital", category: "academic", weight: 1 },
  { phrase: "it is important to note", category: "hedging", weight: 1 },
  { phrase: "it is worth noting", category: "hedging", weight: 1 },
  { phrase: "in terms of", category: "hedging", weight: 1 },
  { phrase: "with regard to", category: "transition", weight: 1 },
  { phrase: "with respect to", category: "transition", weight: 1 },
  { phrase: "in light of", category: "transition", weight: 1 },
  { phrase: "plays a crucial role", category: "emphasis", weight: 2 },
  { phrase: "plays a vital role", category: "emphasis", weight: 2 },
  { phrase: "plays a pivotal role", category: "emphasis", weight: 2 },
  { phrase: "it is essential to", category: "hedging", weight: 1 },
  { phrase: "it is crucial to", category: "hedging", weight: 1 },
  { phrase: "in conclusion", category: "transition", weight: 1 },
  { phrase: "to summarize", category: "transition", weight: 1 },
  { phrase: "first and foremost", category: "emphasis", weight: 2 },
  { phrase: "comprehensive understanding", category: "academic", weight: 2 },
  { phrase: "holistic approach", category: "academic", weight: 2 },
  { phrase: "facilitate", category: "academic", weight: 1 },
  { phrase: "utilize", category: "academic", weight: 1 },
  { phrase: "implement", category: "academic", weight: 1 },
];

export const CONNECTIVES = {
  additive: ["and", "also", "moreover", "furthermore", "additionally", "besides", "likewise", "similarly"],
  adversative: ["but", "however", "yet", "nevertheless", "nonetheless", "although", "though", "whereas", "while", "conversely"],
  causal: ["because", "therefore", "thus", "hence", "consequently", "accordingly", "so", "since"],
  temporal: ["then", "next", "finally", "subsequently", "meanwhile", "afterward", "previously", "first", "second", "third"],
};

export const HIGH_FREQUENCY_WORDS = new Set([
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "i", "it", "for",
  "not", "on", "with", "he", "as", "you", "do", "at", "this", "but", "his", "by",
  "from", "they", "we", "say", "her", "she", "or", "an", "will", "my", "one",
  "all", "would", "there", "their", "what", "so", "up", "out", "if", "about",
  "who", "get", "which", "go", "me", "when", "make", "can", "like", "time", "no",
  "just", "him", "know", "take", "people", "into", "year", "your", "good", "some",
  "could", "them", "see", "other", "than", "then", "now", "look", "only", "come",
  "its", "over", "think", "also", "back", "after", "use", "two", "how", "our",
  "work", "first", "well", "way", "even", "new", "want", "because", "any", "these",
  "give", "day", "most", "us", "is", "are", "was", "were", "been", "being", "has",
  "had", "does", "did", "am", "very", "more", "much", "such", "own", "same",
  "should", "must", "may", "might", "still", "here", "where", "why", "each",
  "every", "both", "few", "many",
]);

export const FORMULAIC_NGRAMS = {
  bigrams: [
    "it is", "this is", "there are", "there is", "we can", "you can",
    "in order", "as well", "such as", "due to", "based on", "in the",
    "of the", "to the", "for the", "on the", "by the", "with the",
    "is a", "are a", "was a", "be a", "as a", "have a",
    "important to", "necessary to", "essential to", "crucial to",
    "ability to", "order to", "need to", "want to", "have to",
    "can be", "will be", "would be", "could be", "should be", "must be",
  ],
  trigrams: [
    "it is important", "it is essential", "it is crucial", "it is necessary",
    "in order to", "as well as", "due to the", "based on the",
    "one of the", "some of the", "many of the", "most of the",
    "the fact that", "in the context", "on the other", "at the same",
    "is one of", "are some of", "is a key", "plays a crucial",
    "plays a vital", "plays an important", "in this article",
    "in this essay", "we will explore", "let us delve", "let's explore",
    "when it comes", "it comes to", "comes to the",
  ],
};
